Job Preparation Analysis
Recode-Hive/Stackoverflow-Analysis pull request #108
Opened 2024-05-17 11:49 UTC by Navyazitya

The issue I worked on is: #82 
I made a Job preparation Analysis. 
![Screenshot (41)](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/151536566/440ad1d2-6b88-4c37-b21e-416c71be5292)
![Screenshot (42)](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/151536566/7eacdd1a-e60d-43f6-b556-fef6c69ae2c6)
![Screenshot (43)](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/151536566/86fb5bc9-3b1e-4f2d-af9d-3839f5f673ca)
![Screenshot (44)](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/151536566/9069dc5b-63da-42be-8d7c-8346e792b8d2)
The analysis includes:
I-->imported the dataset and handled missing values.
-->Removed duplicate columns and rows to ensure data integrity.
-->Analyzed salary trends over the years and observed an increasing trend in median salaries.
-->Compared salaries between different countries, identifying the United States as having the highest median salary.
-->Visualized salary distributions across different developer roles, identifying back-end developers as having the highest salaries.
-->Explored language preferences for top developer roles, indicating the highest paying languages for roles like Data Scientist and Web Developer
-->Examined regional variations in salaries, highlighting countries with the highest pay such as Ireland, New Zealand, and the United States.
-->Visualized the relationship, noting that both slightly satisfied and highly satisfied individuals span a wide range of salaries.

I visualized all the salary trends, geographical trends and the skill trends and prepared all the analytical conclusions of the analysis. It gives all the suggestions that one need to get an high paying job.

2024-05-18 12:55 UTC, sanjay-kv requested changes
Hi I liked the idea, but we dont need separate ipynb file, can u combine to the current main ipynb file please.

2024-05-18 14:01 UTC, Navyazitya commented
> Hi I liked the idea, but we dont need separate ipynb file, can u combine to the current main ipynb file please.

Sir @sanjay-kv  Can you brief me How can we do that please..?

2024-05-19 10:41 UTC, Navyazitya commented
Sir @sanjay-kv , I did the changes and added it locally could you please check that and let me know whether I did right or not..

2024-05-19 11:40 UTC, sanjay-kv approved these changes

2024-05-19 11:40 UTC, merged