EDA on stack overflow dataset-2018
Recode-Hive/Stackoverflow-Analysis pull request #66
Opened 2024-05-13 10:08 UTC by Navyazitya

![bit of analysis](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/151536566/3f9f7a19-a1e2-433f-9c2d-0ad74d577fc9)
![bit of anlysis done](https://github.com/Recode-Hive/Stackoverflow-Analysis/assets/151536566/2baf42f3-ff40-41ae-a903-60017448d217)
I added more visualizations , found out the correlations between them and then performed analysis on different sections like employment, job satisfaction, language used next year and all.

2024-05-14 06:11 UTC, sanjay-kv commented
can you refer to the issue you raised. 
you can do that by typing # and find relevant issue . 
sample #74

2024-05-14 06:55 UTC, Navyazitya commented
#27 this is the issue that I worked on sir.

2024-05-14 14:52 UTC, sanjay-kv requested changes
We dont need different ipynb for different analysis make into one

2024-05-14 15:35 UTC, Navyazitya commented
All the before code is there in this sir. I combined everything and only added that sir.. @sanjay-kv .

2024-05-15 12:12 UTC, Navyazitya reviewed
This is the same ipynb file sir. I am just adding different analysis to the same notebook itself . All the before code is there in this sir. I combined everything and only added that sir.. You can merge this file sir @sanjay-kv anjay-kv .
Sir, what about the doubt I asked sir. Like I completed this issue sir. Can I stop this issue here or should I add anything else in this sir.

2024-05-18 12:46 UTC, sanjay-kv approved these changes
good to go

2024-05-18 12:46 UTC, merged